pipeline {
    agent {
        docker {
            image 'python:3.10'
        }
    }
    environment {
        DOCKERHUB_CREDENTIALS = credentials('docker-hub-creds')
        DOCKER_REGISTRY = 'yanivomc'
        REPO_NAME = 'fe-exam'  // Change to 'be-exam' for backend pipeline
        IMAGE_TAG = "${env.BUILD_NUMBER}"
        
    }
    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'workshop/argo-jenkins-exam', url: 'https://github.com/gald10102/devopshift-welcome.git'
            }
        } //end of clone stage
        stage('Lint & Security Scan') {
            steps {
                //running flake on fe 
                sh """
                    cd exam-code/docker/fe
                    ls -l
                """
                //sh 'cd exam-code/docker/fe'
                //sh 'ls -l'
               //flake8 /
            }
        }
    }
}
